openapi: 3.0.3
info:
    title: TODO API
    version: 1.0.0
    description: >
        API de gestion d'une TODO List.
servers:
    -   url: http://localhost:8080
        description: Serveur local de développement

tags:
    -   name: tasks
        description: Opérations sur les tâches

paths:
    /tasks:
        post:
            tags: [ tasks ]
            summary: Créer une tâche
            operationId: createTask
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TaskCreateDto'
            responses:
                '201':
                    description: Tâche créée avec succès
                    headers:
                        Location:
                            description: URL de la ressource créée
                            schema:
                                type: string
                                example: /tasks/1
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TaskResponseDto'
                '400':
                    description: Paramètre invalide
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorDto'
        get:
            tags: [ tasks ]
            summary: Récupérer toutes les tâches
            operationId: getTasks
            parameters:
                -   in: query
                    name: todo-only
                    required: false
                    description: Si true, retourne uniquement les tâches non faites
                    schema:
                        type: boolean
                        example: true
            responses:
                '200':
                    description: Tâches trouvées
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/TaskResponseDto'
                '204':
                    description: Aucune tâche trouvée

    /tasks/{id}:
        parameters:
            -   in: path
                name: id
                required: true
                description: Identifiant numérique de la tâche
                schema:
                    type: integer
                    minimum: 1
        get:
            tags: [ tasks ]
            summary: Récupérer une tâche
            description: Récupérer une tâche par son identifiant
            operationId: getTaskById
            responses:
                '200':
                    description: Tâche trouvée avec succès
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TaskResponseDto'
                '404':
                    description: Tâche non trouvée
        delete:
            tags: [ tasks ]
            summary: Supprimer une tâche
            operationId: deleteTaskById
            responses:
                '204':
                    description: Tâche supprimée avec succès
                '404':
                    description: Tâche non trouvée
        put:
            tags: [ tasks ]
            summary: Modifier une tâche
            operationId: updateTaskById
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TaskUpdateDto'
            responses:
                '204':
                    description: Tâche modifiée avec succès
                '404':
                    description: Tâche non trouvée
                '400':
                    description: Paramètre invalide
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ErrorDto'

components:
    schemas:
        Task:
            type: object
            description: Représentation d'une tâche
            properties:
                id:
                    type: integer
                    example: 1
                title:
                    type: string
                    nullable: false
                    example: Acheter du lait
                description:
                    type: string
                    nullable: true
                    example: 2L demi-écrémé
                done:
                    type: boolean
                    nullable: false
                    example: false
            required:
                - id
                - title
        TaskResponseDto:
            type: object
            properties:
                id:
                    type: integer
                    example: 1
                title:
                    type: string
                    example: Acheter du lait
                description:
                    type: string
                    example: 2L demi-écrémé
                done:
                    type: boolean
                    example: false
        TaskCreateDto:
            type: object
            properties:
                title:
                    type: string
                    maxLength: 50
                    example: Acheter du lait
                description:
                    type: string
                    maxLength: 255
                    example: 2L demi-écrémé
            required:
                - title
        TaskUpdateDto:
            type: object
            properties:
                title:
                    type: string
                    maxLength: 50
                    example: Acheter du lait
                description:
                    type: string
                    maxLength: 255
                    example: 2L demi-écrémé
                done:
                    type: boolean
                    example: false
            required:
                - title
        ErrorDto:
            type: object
            properties:
                field:
                    type: string
                    example: title
                message:
                    type: string
                    example: Le titre est obligatoire et doit faire maximum 50 caractères